### PR TITLE
Clasqa db access

### PR DESCRIPTION
**Pull request by rtysonCLAS12**
This introduces two new classes to access the Quality Assurance database from json files by interfacing to the clasqaDB c++ code. The first class allows to quickly merge json files, and the second provides the interface to clasqaDB. This second class is then used in clas12reader to allow skimming of events based on QA requirements. This works by first calling c12.applyQA with the absolute path to a json file containing the QA database. Requirements can then be added with addRequirement("Requirement"), or isOkForAsymmetry(true) which only allows events that have been identified as suitable for asymmetry measurements.

An example is provided in RunRoot/Ex9_QualityAssurance.C and instructions have been added to the README.

Some things to note:
- To make these optional, compiling the two new classes and adding to the clas12reader are dependent on an environment variable being set to the home directory of clasqaDB. Clas12Banks/CMakeLists was modified to simplify the logic behind compiling certain classes or not based on environment variables being set.
- The clasqaDB is a header library with definitions of the functions in the header file. This causes a multiple definition error when including the library in a project as these functions are not inlined (see https://stackoverflow.com/questions/51602927/why-linker-error-multiple-definitions-with-only-one-library-using-cmake-3-4 for more details). The "-Wl,--allow-multiple-definition" linker options were added to the project (if the QADB_HOME environment variable is set) to avoid this issue.

### CODE REVIEW

**Comment by dglazier** [comment]
Some points to consider,

1) Can the qadb_reader be more self contained ? Do we need to have the extra data members in clas12reader (other than _qa ?) i.e. move 
    bool _applyQA{false};
    std::vector<std::string> _reqsQA;
    bool _reqOKAsymmetry{false};
    bool passQAReqs();

to qadb_reader.
Then you just have a getter for qa that you can set things on directly. We also need to make sure these parameters get passed on when using HipoChain, which means in 
clas12reader::clas12reader(const clas12reader &other,std::string filename,std::vector<long> tags)

2) _qa itself looks like a raw pointer with no ownership, i.e. it will memory leak. This should never happen. Always use unique_ptr (and pass the raw pointer from unique_ptr::get() ). Also _qa is not initiliased which can lead to untraceable crashes. Should at least have, 
 qadb_reader * _qa = {nullptr};

but better
unique_ptr<qadb_reader> _qa ={nulltpr};

then in .cpp
 _qa.reset(new qadb_reader{jsonFilePath} ) ; //now this memory will be freed when clas12reader is deleted
Also you do not need an additional bool as you can just test on existence of pointer
  if(_qa.get())
    if(_qa->passQAReqs()==false) return;

3) I avoid string char comparisons as they are much slower
e.g. req=="Golden"
In type of situation I would use class enum (https://www.geeksforgeeks.org/enum-classes-in-c-and-their-advantage-over-enum-datatype/). It looks like this is probably feeding down from the QADB though, so perhaps nothing can be done without changing that.
enum class QAType{Golden,MarginalOutlier,TotalOutlier};
req==QAType::Golden

**Comment by rtysonCLAS12** [comment]
Thanks, I've now included these comments in the code:

1-2: Most of the previous clas12reader data members are now in the qadb_reader. clas12reader still contains a unique_ptr<qadb_reader> and has a getter function to return the raw pointer. This is copied over in the clas12reader copy constructor. qadb_reader is now initialised with a run number, and the passQAReqs function takes in an event number. 

3. Rather than have a string char comparison for "Golden" I changed slightly the way that users can require only Golden events, by introducing a new method isGolden(true) in the qadb_reader. This is more logical in any case because a golden event won't present any other defects.

**Comment by dglazier** [comment]
Just to check Richard, can I run through the whole data file and just check if an event passes QA conditions. This might be useful, so at the data fitting stage you could just filter events based on QA, rather than having to rerun the data ?

**Comment by rtysonCLAS12** [comment]
Hi Derek,

When running through a file using the clas12reader, you can check for defects using, for example:
 while(c12.next()) {
    if(c12.getQAReader()->hasDefect("MarginalOutlier")){
      cout<<"Marginal Outlier "<<endl;
    }
  }

However, I just noticed a bug when trying this out. Protecting the getQAReader function declariation with #ifdef $CLAS_QADB leads to the error " no member named 'getQAReader' in 'clas12::clas12reader'" at runtime, and I need to protect the function declaration to make the QA code optional as the return type of the function is "qadb_reader". 

I think this means that I need to change the way the qadb_reader is used, for example by declaring it and adding the requirements to skim outside of the clas12reader before passing it to the reader for skimming, unless you can think of a better way of avoiding this issue?

**Comment by dglazier** [comment]
Hi Richard,
  I don't think I understand why you get the run time error. Is the enviroment variable CLAS_QADB consistent for compiliation and run time ?
Cheers
Derek

**Comment by rtysonCLAS12** [comment]
Hi Derek,

CLAS_QADB is defined in the CMakeLists.txt file at line 47 with "add_definitions(-DCLAS_QADB)". I'm not sure what you mean by "Is the enviroment variable CLAS_QADB consistent for compiliation and run time ?".

Cheers,
Richard

**Pull request merged**
